// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvYwqJJxcErjd7uI-DXrBa72Zj5Le2h0',
    appId: '1:853224665647:web:d2c685a40cbc8bce664cda',
    messagingSenderId: '853224665647',
    projectId: 'magic-wand-battle',
    authDomain: 'magic-wand-battle.firebaseapp.com',
    storageBucket: 'magic-wand-battle.firebasestorage.app',
    measurementId: 'G-CWBHGXV71J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfzdXElLl-Hxv7h6JXVJRWyYPI7ni3YU',
    appId: '1:853224665647:android:5e30129bdde42270664cda',
    messagingSenderId: '853224665647',
    projectId: 'magic-wand-battle',
    storageBucket: 'magic-wand-battle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VPJ6l_sEiQgjq3o94_ITj04Cm5zMvOY',
    appId: '1:853224665647:ios:01914a54879a6577664cda',
    messagingSenderId: '853224665647',
    projectId: 'magic-wand-battle',
    storageBucket: 'magic-wand-battle.firebasestorage.app',
    iosBundleId: 'com.featmultimedia.magicwandbattle',
  );
}
